# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    chaton:
        class: AppBundle\Application
        arguments:
            - "@chaton.chat"
            - "@event_dispatcher"

    chaton.chat:
        class: AppBundle\Chat\Chat\ConsoleChat