# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    chaton:
        class: Chaton\Chaton
        arguments:
            - [ ]
            - "@logger"

    command.chat:
        class: Chaton\Command\ChatCommand
        arguments:
            - "@chaton"
        tags:
            - { name: "console.command" }